### ISSUE TITLE
Use the module to send data to TTN

### ISSUE THREAD

**Issue by niosp** [xreef/EByte_LoRa_E22_Series_Library#23]
Hello, is there any information available regarding the usage with ttn? Can't find anything about that in the repo like AppKey, EUI etc..

**Comment by xreef** [comment]
Hi,
no, I think nobody creates a wrapper for a gateway (exists an SDK to do that).
Probably because TTN It's only a possible implementation, and It's a protocol maintained by big factories.
Implementing a simple gateway with free code and service is quite simple, and I think It's a good choice.
Bye Renzo
